#POSTGRESQL

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: desarrollo_db_PG

test:
  <<: *default
  database: prueba_db_PG

production:
  <<: *default
  database: produccion_db_PG


#SQLITE3

#test:
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#  database: prueba_db
#
#development:
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#  database: db/development.sqlite3